# § для использования цветов
# Версия конфигиа 0.3
message:
  # Системное
  prefix: "§6[§4PrizrakkPlugin§6] §f"
  noperm: "У вас не прав на эту команду!"
  reload: "Плагин перезапущен!"
  noconsole: "Команда доступна только игроку!"
  offline: "Этот игрок оффлайн"
  error: "Произошла ошибка при выполнение команды!"
  # Сменя дня и ночи
  day: "Установлено дневное время"
  night: "Установлено ночное время"
  # Вход и выход
  join: "Игрок %player% зашел на сервер"
  left: "Игрок %player% вышел с сервера"
  # Варны
  addwarn: "Вы успешно выдали варн игроку: "
  delwarn: "Вы успешно удалили варн игроку: "
  add-warn-view: "Вы получили варн! от Администратора %admin% !"
  del-warn-view: "Вам сняли варн! Ведите себя хорошо!"
  # Прочее
  health: "Вы исцелены!"
  feed: "Вы были покормлены!"
  gm: "Ваш игровой режим изменился на"
  # не реализовано
  success: "Поздравляю вы забрали свой подарок за отыграное время!"
  motd: "A minecraft Server"
config:
  mconline:
    enable: false
    port-bind: 11111
  version: 0.6
  time-reward: 3000 //В тиках
  reward-item: diamond //писать как и пишет в /itemdb для 100% результата
  reward-count: 1
  mysql:
    user: "user"
    password: "querty123"
    url: "jdbc:mysql://127.0.0.1:3306/PluginDataBase"
