# § для использования цветов
# Версия конфигиа 0.3

config:
  enable: true
  debug: false
  warncount: 3
  console-out-log-command: true
  mysql:
    user: "user"
    password: "querty123"
    url: "jdbc:mysql://127.0.0.1:3306/PluginDataBase?autoReconnect=true"
  discord:
    enable: false
    token: ""
    chat: ""
    console: ""
