# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build pre-release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with plugin
      run: mvn dependency:tree -Ddetail=true -B package --file pom.xml
    - name: Moving the plugin.
      run: |
          mkdir -p /home/runner/work/PrizrakkPlugin/PrizrakkPlugin/builds
          mv /home/runner/work/PrizrakkPlugin/PrizrakkPlugin/target/PrizrakkPlugin-1.jar /home/runner/work/PrizrakkPlugin/PrizrakkPlugin/builds
    - name: Upload plugin
      uses: actions/upload-artifact@v1
      with:
        name: plugin
        path: builds
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
